uprn is now m2m with title [WIP]
alphagov/land-availability-lr pull request #21
Opened 2017-05-31 15:32 UTC by davidread

* [ ] update model
* [ ] update read serializer (Andrea?)
* [ ] update importer

2017-05-31 15:35 UTC, andreagrandi requested changes

2017-05-31 15:35 UTC, andreagrandi commented on landavailability/tests/lr/test_models.py
> +        uprn.titles.add(title)
This definitely tests if we can associate a Title to a Uprn. We should also include a test to verify the opposite thing: if we can add a Uprn to a Title.

2017-05-31 16:18 UTC, davidread commented on landavailability/tests/lr/test_models.py
> +        uprn.titles.add(title)
I've added that in now

2017-05-31 16:58 UTC, davidread commented
I've updated the importer now. Did you want to do the serializer, or shall I?

2017-06-01 08:18 UTC, andreagrandi commented
@davidread yes I can do the serializer. Can you please fix the failing tests first so I can continue from there? Cheers

2017-06-01 17:06 UTC, davidread commented
Now I've remembered to add the migration file to the repo, only one test should fail: tests/lr/test_views.py::TestUprnLookupView::test_lr_view_lookup_uprn which is due to the serializer

2017-06-05 10:47 UTC, andreagrandi commented
@davidread it should be all fixed now. Coveralls is not very happy at the moment, but we can improve it later :)

2017-06-05 14:14 UTC, davidread commented
@andreagrandi I'm good with your bits. Do you want to review the rest and merge if happy?

2017-06-05 14:18 UTC, merged